### ISSUE TITLE
Requiring python-xmlsec 0.6.0 instead of vendoring patched 0.3.1

### ISSUE THREAD

**Issue by vstoykov** [orcasgit/py-wsse#1]
I see that there is a new version of `python-xmlsec` from a month ago which includes the pach mentioned in the docs (https://github.com/mehcode/python-xmlsec/pull/4/files)

If everything works correctly I think that will be better to remove the vendored package and set `xmlsec>=0.6.0` in `install_requires`.

**Comment by carljm** [comment]
Indeed, this would be great. Not sure when I can get to it, but if you're able to verify that it works and submit a pull request making the change, I'd be happy to merge it!
