### ISSUE TITLE
Does Py-WSSE support WS-SecureConversation?

### ISSUE THREAD

**Issue by Heilage** [orcasgit/py-wsse#4]
I have a somewhat specific issue. The service I am trying to establish a connection to appears to require WS-SecureConversation, which, as far as I can gather, happens in the form of a pre-request handshake between the client and the server to get a security context token that can be used in subsequent requests.

Does this library support this? It's not mentioned, and it could explain why I can't get my module to work. Any help would be appreciated.

**Comment by carljm** [comment]
Not supported, no. This library supports exactly what I needed for my use case and no more :/ anything else you'll need to implement yourself.
