### ISSUE TITLE
py-wsse cannot been installed

### ISSUE THREAD

**Issue by lopow** [orcasgit/py-wsse#6]
I cannot install py-wsse on my computer. I have an error py-config is missing.

**Comment by brad** [comment]
@lopow That means you need the python development headers. Also needed are the headers for OpenSSL, libxml2, and libxmlsec1. See [the docs](https://py-wsse.readthedocs.io/en/latest/#prerequisites) Installing those is different depending on your OS. For debian based Linux you would do:
```
sudo apt-get install python-dev libssl-dev libxml2-dev libxmlsec1-dev
```

**Comment by lopow** [comment]
how can I get this using windows an pip
