### ISSUE TITLE
error: pkg-config is not installed

### ISSUE THREAD

**Issue by lopow** [orcasgit/py-wsse#7]
C:\>pip install py-wsse
Collecting py-wsse
    Using cached py-wsse-0.1.tar.gz
    Collecting xmlsec>=0.3.1.orcas1 (from py-wsse)
    Using cached xmlsec-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    Installed c:\users\andrej\appdata\local\temp\pip-build-9oylxw3_\xmlsec\.eggs\setuptools_cy
    running egg_info
    creating pip-egg-info\xmlsec.egg-info
    writing pip-egg-info\xmlsec.egg-info\PKG-INFO
    writing requirements to pip-egg-info\xmlsec.egg-info\requires.txt
    writing dependency_links to pip-egg-info\xmlsec.egg-info\dependency_links.txt
    error: pkg-config is not installed
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Andrej\AppData\Local\Temp\pip-build-9oylxw3_\xmlsec\

**Comment by konvalik** [comment]
Hi lopow, 

i have the same problem. Do you find any solution? 

Thanx
